name: Read and Write to JSON files
description: Extracts a value of a property specified as dot-separated path from defined JSON file
author: "amochkin"
inputs:
  file:
    description: "Path to JSON file; default is `package.json`"
    default: "package.json"
  mode:
    description: "Mode of operation (`read`/`write`); default is `read`"
    default: "read"
  property:
    description: "Dot-separated path to property (for example `a.b`)`"
    required: true
  value:
    description: "Value to write to property, required for `write` mode"
  valueType:
    description: "Type of value to write to property (`string`/`number`/`boolean`/`object`); default is `string`"
    default: "string"
  nolog:
    description: "Do not output value to the log; default is `false`"
    default: "false"
  fallback:
    description: "Fallback file to use if file is not found"
  override:
    description: "Override read value with this value"
  useOverride:
    description: "Flag: Use override value instead of read value"
    default: "false"
runs:
  using: "node16"
  main: "dist/index.js"
branding:
  icon: settings
  color: blue
outputs:
  value:
    description: "Value of property (only if mode is `read`)"
